### ISSUE TITLE
Return 0.2x0.2 degree uncertainty polygon for obscured observations

### ISSUE THREAD

**Issue by matthewpaulking** [inaturalist/iNaturalistAPI#109]
Apologies if this has been brought up elsewhere, but I would find it very handy to plot the 0.2x0.2 degree  area for observations that are obscured. 

Is it currently possible to access the vertices/coordinates of the obscured area with the node API?

**Comment by kueda** [comment]
Can you describe the use case? IMO, that information would be redundant with what's already in the response. You've already got `obscured`, which tells you that the coordinates have been obscured within the 0.2x0.2 degree cell containing the coordinates, so if you wanted to draw that in the client you can just do so (e.g. SW corner for 1.22,1.33 would be 1.2,1.2, NE corner would be 1.4,1.4).

**Comment by matthewpaulking** [comment]
Ah ok, I wasn't understanding these were absolute 0.2x0.2 degree grids. If I can calculate them, I agree there's no need to add anything to the API.

Many thanks for the clarification!
