### ISSUE TITLE
fetch projects by featured status

### ISSUE THREAD

**Issue by alexshepard** [inaturalist/iNaturalistAPI#112]
iOS displays projects that have been "featured" by iNat. it would be great if there was a way to query the api for featured projects.

**Comment by pleary** [comment]
I added a `featured` param to the node projects search endpoint https://api.inaturalist.org/v1/projects?featured=true . We may need to tweak the sorting of results for this endpoint, or this query when you also add `lat` and `lng` params to more closely match the results returned by Rails
