### ISSUE TITLE
fetch projects by location

### ISSUE THREAD

**Issue by alexshepard** [inaturalist/iNaturalistAPI#113]
iOS displays projects that are "nearby" the user. it would be great if there was a way to query the api for projects near a lat/long coordinate.

**Comment by kueda** [comment]
For clarity, you're asking for something like https://www.inaturalist.org/projects.json?latitude=38&longitude=-121 in the Node API, right?

**Comment by pleary** [comment]
We now have a projects search endpoint in the node API. I haven't added it to the documentation yet, but will do that this week. You can fetch projects by location with: https://api.inaturalist.org/v1/projects?lat=42&lng=-70
