### ISSUE TITLE
Weight taxon/autocomplete results by request locale

### ISSUE THREAD

**Issue by kueda** [inaturalist/iNaturalistAPI#115]
This will probably start out as R&D and might not end up being possible, but here's the desired outcome a la @tiwane: currently when you send the query `fu` you get back Aves as the first result because it has the Icelandic name "Fuglar," the Norwegian name "Fugler," and a lot of observations, and while that makes a lot of sense for people in Iceland and Norway, English speakers are probably expecting something more like Fungi as the top result.

Similarly, we don't want to simply exclude results that match names in the non-target lexicon, b/c then people can't look things up by those names, which will be a serious problem where multiple languages are in common use (Canada, New Zealand, etc.).

So my proposal is to *weight* taxon autocomplete results that match the request locale more than those that don't, so if you search for `fu` you would still get Aves but not as the top result. Ideally this would respect the `locale` param in the URL and then the authenticated user's locale.

Tony, if you have more examples than the `fu` one I think that would be really helpful in testing this.

**Comment by tiwane** [comment]
Two other examples pointed out by Jesse Rorabaugh:

He types in "D" or "Di" and to get dicots but Animals appears at the top for both of those.

And: "The big offender seems to be animals. This is the first entry which comes up if I hit a, b, d, h, i, k, p, r, t, y, and z."

**Comment by kueda** [comment]
I can do this but I *think* I will need to make `names` a `nested` object within the taxa index, which will require recreating the entire taxa index for one thing, but might have some performance implications. Does that raise any red flags, @pleary? My main issue is that in order to give a higher score to taxa that with names in a particular locale, I need to be able to do a query like "show me taxa that have at least one name where the name.name = foo AND the name.locale = es," and I haven't quite found a way to do that except via a nested object. Most of my attempts to do without the nesting end up with queries like "show me taxa that have name.name = foo and maybe another name where name.locale = es" which ends up over-selecting.

If if would be easier I can push some code to a branch for consideration.

FWIW, I think #117 would require even further nesting of `place_taxon_names` inside of `names` (they're already there, just not nested).

**Comment by pleary** [comment]
That sounds OK to me. The taxon index isn't that big, so this shouldn't have much of a performance impact. It also shouldn't affect the data structure, so presumably all responses will remain the same

**Comment by kueda** [comment]
Yeah, so far the main effect outside of autocomplete seems to be that I had to re-write a few queries to use the `nested` query.
