### ISSUE TITLE
List of Taxon ID's

### ISSUE THREAD

**Issue by devinfd** [inaturalist/iNaturalistAPI#119]
Hello there,

I'm very impressed with iNaturalist and excited to see that there is an API available. I am the creator of Wildlife Rehabilitation MD (wrmd.org) and am looking into ways that we can benefit from your work. What would make querying your API easier would be to know the taxon ID's of all the species (birds, mammals, reptiles and amphibians) that WRMD works with. Is there a resource available to get those ID's with their genus species names? I would hate to have to query your database for each name and scrape off the taxon_id.

Thanks!

**Comment by loarie** [comment]
you can use the taxon search API, e.g. http://api.inaturalist.org/v1/taxa/autocomplete?q=American%20Robin

Please use the google group or help@inat for help inquiries and reserve github for software dev

**Comment by devinfd** [comment]
Sorry I didn't know there is a google group.

ps: Yes I am aware of the ```http://api.inaturalist.org/v1/taxa/autocomplete``` endpoint but I will be hitting it tens of thousands of times in order to get those taxon IDs.
