### ISSUE TITLE
Add 'Application' to observations search API 

### ISSUE THREAD

**Issue by loarie** [inaturalist/iNaturalistAPI#122]
So, for example, I could search for species represented by observations of:
birds
made this month
near me
made with an iPhone or Android

the idea being that this will create a more mobile appropriate stream of mission targets

**Comment by pleary** [comment]
I added the ability to search on the integer `oauth_application_id`. So you can get top species from the iNat iOS and Android apps with http://api.inaturalist.org/v1/observations/species_counts?oauth_application_id=2,3&per_page=10

There is currently no way to look up or list the oauth applications (like we have with controlled terms in http://api.inaturalist.org/v1/docs/#!/Controlled_Terms/get_controlled_terms). Is this OK for now, or do we want a way to list apps to search on so their IDs can be fetched, or do we need some other helper params specifically for the iNat iOS and Android apps?

**Comment by kueda** [comment]
Scott, can you close this if Patrick's solution is sufficient?

**Comment by kueda** [comment]
Assuming this is done. If not, please re-open.
