### ISSUE TITLE
requesting additions to the /observations/:id endpoint

### ISSUE THREAD

**Issue by alexshepard** [inaturalist/iNaturalistAPI#13]
in `/observations/:id`, it would be helpful to the iOS app to have:

   * an icon for the taxon object
   * identifications, including:
    * user.id
    * user.icon
    * user.login
    * taxon.id
    * taxon.icon
    * taxon.common_name
    * taxon.scientific_name
    * body
    * datetime
   * faves, including:
    * user.id
    * user.icon
    * user.login
    * datetime

I forgot to mention when we were talking, that in the iOS we're also `identification.current`, which I _think_ is just shorthand for "is this the most recent observation by this user?" so we could probably calculate it on the client side if need be.

Thanks!

**Comment by alexshepard** [comment]
if it's not too late, as I'm working with this, I just realized that the `user` object under `/comments` that is returned by `/observations/:id` doesn't have an icon url. Is this something that could be added?

**Comment by pleary** [comment]
OK I think this is pretty much all set. `/observations/:id` now includes everything in your first comment, and users for comments. I'll update the swagger doc today.
