### ISSUE TITLE
500 Internal Server Error - Can't access over 10,000th observation (with OAuth)

### ISSUE THREAD

**Issue by vdalv** [inaturalist/iNaturalistAPI#134]
Hi, I'm getting a 500 error when I try to access any observations over 10,000, and this is w/ proper authentication being in place.

This line of code (from the [docs](https://www.inaturalist.org/pages/api+reference)) works fine: `puts RestClient.get("#{site}/users/edit.json", headers)`
But this code throws a 500 error:
`puts RestClient.get("https://api.inaturalist.org/v1/observations?taxon_id=42051&per_page=100&page=101", headers)`

^Setting page=100 works fine though.

Side-note: The docs is incorrect when it [states only the 1st 100 pages can be accessed](https://i.imgur.com/b5lfwW6.png). For example, when you set per_page=50, you can [access page 200 just fine](https://api.inaturalist.org/v1/observations?taxon_id=42051&per_page=50&page=200). But [setting page=201](https://api.inaturalist.org/v1/observations?taxon_id=42051&per_page=50&page=201) returns a 500 error.

**Comment by pleary** [comment]
The API largely queries Elasticsearch, which has a `max_result_window` setting which defaults to 10k results (see https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-from-size.html). We are sticking with this default setting, so more than 10k results for a single search are not available. I've updated the response code and error message with this happens.

You can avoid the error by changing your search parameters to reduce the result set or change the sort/order to get different results up top. If you really need to access more data, I recommend sorting by ID and using the `id_above` or `id_below` params (based on your sort order). You could for example sort by id ascending, get 100 results, make a new query by adding `id_above=THE_LAST_ID` and repeating until you have the data you need.

**Comment by vdalv** [comment]
Sorry for the extremely delayed response, but yeah I skirted around this issue at the time by tinkering with the search parameters, as you suggest.

If I have time, I'll try to go and update the [docs page](https://www.inaturalist.org/pages/api+reference#get-observations) that states: "Note that while this endpoint doesn't require authentication under normal circumstances, it WILL require it when you request pages higher than 100. If you're going to scrape us, we want to know who you are."
