### ISSUE TITLE
Find observations where license_code == null?

### ISSUE THREAD

**Issue by vdalv** [inaturalist/iNaturalistAPI#135]
Hey, I was just wondering how I could retrieve all of the observations that have a null license_code.

I've tried these, but haven't had any luck: 
http://api.inaturalist.org/v1/observations?license=null&taxon_id=148030
http://api.inaturalist.org/v1/observations?license=&taxon_id=148030
http://api.inaturalist.org/v1/observations?license=none&taxon_id=148030

Thanks

**Comment by kueda** [comment]
FWIW, there isn't currently a way to do this and we're kind of on the fence about what the best convention to use for specifying the the absence of a value. Some ideas we've discussed

- `license=null` (fine for `license`, but hard to validate if the value is usually an int, e.g. `taxon_id=null`)
- `without_license=true` (need to add `without_*` params for everything that can be searched for absences)
- `-license` (weird prepending of `-`, but it is concise, also means supporting a lot of extra params)
- `license=-1` or `license=0` (not exactly human-readable)

**Comment by pleary** [comment]
I think this was implemented in #206 with the new `licensed` param. There's still no generic convention and implementation for all similar parameters, but we should have it for observation license which was the subject of this ticket
