### ISSUE TITLE
put site_id for user on node api?

### ISSUE THREAD

**Issue by alexshepard** [inaturalist/iNaturalistAPI#145]
it would be great if we could set the users' site_id using the node api

```
curl -X PUT stagingapi.inaturalist.org/v1/users/alex_tester -H "authorization: $AUTH_ID" -d '{
  "user": {
    "site_id": 8
  }
}'
```

doesn't seem to work

**Comment by pleary** [comment]
I think this is a matter of the the response not indicating the change has been made, but the site_id does actually update. Could that be the case?

Elasticsearch changes aren't available immediately, rather new data appears every 1 second, or when the index is specifically "refreshed". I made a change in inaturalist/inaturalist@8b3db7b that refreshed the User index after updating, which is something we needed to do for other object update methods and I forgot to add to Users. I deployed that to staging if you want to test there

**Comment by alexshepard** [comment]
looks great on staging, thanks!

**Comment by pleary** [comment]
Can this be closed now Alex?

**Comment by alexshepard** [comment]
Yes, thank you Patrick.
