### ISSUE TITLE
delay between add fave on Rails API, new fave showing up in node API

### ISSUE THREAD

**Issue by alexshepard** [inaturalist/iNaturalistAPI#15]
It looks like when I fave something via the rails api, it takes a minute to show up in the node api. 

This is problematic for the iOS app if we're displaying an observation from the node api, want to add a fave to that observation by making a request to rails, and then expect to refresh from the node api and populate our UI showing the user that the fave has happened.

I haven't looked to see if this same behavior is exhibited to other interactive actions on observations, like adding a comment or an identification or etc.

**Comment by pleary** [comment]
I made it so the requests shouldn't get cached on the backend, and include no-cache headers. I'd be interested to see how that looks. There is usually a ~1second delay for data written to elasticsearch to be visible, and some of these operations may do that indexing in a delayed job. If it's still slow now, I can update those places to do indexing real-time and force ES to refresh with the new data.

**Comment by pleary** [comment]
I think we're good to go here. The API is setting no-cache headers for the details requests, and Varnish is properly not caching those requests. Rails is also refreshing the ES index after certain update methods, which ensures the updates are immediately available to the node API. If anyone notices even a small delay with details requests, please reopen this ticket with that info
