### ISSUE TITLE
observations without photos not showing up on range maps

### ISSUE THREAD

**Issue by naturalistcharlie** [inaturalist/iNaturalistAPI#161]
apologies if this is the wrong place.
A ton of observations recently disappeared from the range maps, causing lots of problems. It looks like nothing without a photo is still on the maps. For instance https://www.inaturalist.org/taxa/48463-Pinus-jeffreyi has a bunch... but there are lots of others. I've spent a ton of time putting a bunch of data in here for range extensions, ecology work, etc, and now they don't show on the taxon maps and thus taxon page, observations, or ID page any more. Please help!

**Comment by kueda** [comment]
Discussion at https://groups.google.com/forum/#!topic/inaturalist/aSGn7iEa03I, proposed changes at https://github.com/inaturalist/inaturalist/issues/2072
