### ISSUE TITLE
include iconic taxon name everywhere we include an iconic taxon ID

### ISSUE THREAD

**Issue by kueda** [inaturalist/iNaturalistAPI#17]
Iconic taxon IDs are specific to individual instances of the database, while names should be universal. This makes it awkward to use iconic taxa from endpoints in our API because a client has to hardcode mappings from IDs to names in code (e.g. `{1: "Animalia"}`) which will break when connecting to a different database (e.g. a local development database), or it has to make another request to get more info about those IDs. Including the names would allow clients to use those categories without having to figure out what the numbers mean.

So my proposal is to always include the iconic taxon name every time we show an iconic taxon ID. Maybe this is more of an issue for the Rails app where the ES index gets populated, but I imagine some change will have to be made here too.

This is something @budowski requested in https://github.com/inaturalist/iNaturalistAndroid/issues/134, but I feel like I've also run into it while working on obs search and the identify section.

**Comment by pleary** [comment]
done and deployed. Does this seem OK? http://api.inaturalist.org/v1/taxa/autocomplete?q=Dog

**Comment by kueda** [comment]
Looks good to me. @budowski, does that work for you?

**Comment by budowski** [comment]
Yes, thank you!
