### ISSUE TITLE
Limit string length for taxa search queries

### ISSUE THREAD

**Issue by pleary** [inaturalist/iNaturalistAPI#183]
There are cases of people using taxa autocomplete and setting `q` to a string of over 5000 characters. Elsaticsearch will throw an error if the string is over 1000 character. We could look at logs for a reasonable upper limit - I'd be curious to see any reasonable use cases over 200 characters

**Comment by kueda** [comment]
Seems like 1000 is the absolute upper limit though, so that could be the first hurdle and if we need to narrow it further we can just change the value.
