### ISSUE TITLE
identification created_at not correct

### ISSUE THREAD

**Issue by kueda** [inaturalist/iNaturalistAPI#19]
Compare the created_at value for Identification 5624697 in http://www.inaturalist.org/observations/2882743.json (2016-04-04T19:56:15.679-07:00) with http://api.inaturalist.org/v1/observations/2882743 (2016-04-05T09:56:15+00:00). The node API seems to be showing a created at date a few hours in the future of the real date.

**Comment by pleary** [comment]
I guess Rails stores UTC times in the PG column type `timestamp without time zone`, and node was assuming they were in the timezone of the running node instance. More discussion on that at https://github.com/brianc/node-postgres/issues/429
