### ISSUE TITLE
Computer vision / score_image requests

### ISSUE THREAD

**Issue by edrdo** [inaturalist/iNaturalistAPI#193]
Hi,

For academic research I would be interested in interfacing with the computervision module, in particular the score_image method. We have been developing specialized ML models for Portuguese Flora and we would like to be able to compare results with the iNaturalist service.

The feature is not documented however,  though I can find an example use of it in the Android app: 
 
https://github.com/inaturalist/iNaturalistAndroid/blob/5b8be744b6cfc034f66c2a3f03293cd5cddebfd5/iNaturalist/src/main/java/org/inaturalist/android/INaturalistService.java

Is this the right way to interface with the computer vision service?

**Comment by kueda** [comment]
The computer vision endpoints are not public because there are a number of ways we think they could be misused. We're looking into ways of opening them up with some limitations, but we're not there yet.

**Comment by edrdo** [comment]
Thanks. I hope this is possible in the future, it'd be great. We will use then resort to some manual comparisons of our model using the iNaturalist apps.

**Comment by edrdo** [comment]
I wonder if there are any updates regarding this issue. I've been involved in the development of a CNN model for classifying butterfly species - check out https://rubisco.dcc.fc.up.pt/lepilens/ - and it would be very interesting in comparing our model classifications with those of iNaturalist (which btw was the main source of images used for training). 

One way to go I suppose is to use a modified version of the Android or iOS app to collect results in interaction with the score_image endpoint.  I suppose there is a limit on the number of requests, in any case would that be an acceptable use of the service?

**Comment by kueda** [comment]
@edrdo we are actually currently experimenting with this, but we're still figuring it out. If you want to participate in our tests, please get in touch with [Carrie](https://www.inaturalist.org/people/carrieseltzer).

**Comment by edrdo** [comment]
@kueda I got in touch with Carrie and managed to get access. Thanks a lot.
