### ISSUE TITLE
return quality metrics in response to GET /observations/[ids]

### ISSUE THREAD

**Issue by kueda** [inaturalist/iNaturalistAPI#20]
In order for a client to know if the current user has marked an observation as captive, the client needs to know whether the current user has created a QualityMetric record for the `wild` metric. If it's too much data to load, then something analogous to the `reviewed_by` attribute would suffice, but wouldn't be ideal since the client couldn't distinguish between yes, no, and no vote. I don't think I need this in `GET /observations`, just `GET /observations/[ids]`

**Comment by pleary** [comment]
OK I think this is fixed in ab40930
