### ISSUE TITLE
Add licensed and photo_licensed parameters to the observations API

### ISSUE THREAD

**Issue by kueda** [inaturalist/iNaturalistAPI#206]
- [x] `licensed=true` ~~or `licensed`~~: observations where the license attribute is not null, i.e. it is licensed
- [x] `licensed=false`: observations where the license attribute is null, i.e. they are not licensed
- [x] `photo_licensed=true` ~~or `photo_licensed`~~: observations where the license attribute of at least one photo is not null, i.e. one of the photos is licensed
- [x] `photo_licensed=false`: observations where the photo_license attribute is null for all photos, i.e. obs with no licensed photos

**Comment by viatrix** [comment]
I started looking at this issue, and it’s not clear for me how query string params should look. It’s obvious about `licensed=true` or `licensed=false`. Could you clarify what is meant by **or `licensed`** in **`licensed=true` or `licensed`**, how this `licensed` should look like in the query string? Currently other query string params are checked explicitly to be true or false

**Comment by kueda** [comment]
> Currently other query string params are checked explicitly to be true or false

Yeah, let's just stick with that. My intent was to support a query like `?licensed` to be the same as `?licensed=true`, but if that's inconsistent we can skip that.
