### ISSUE TITLE
Add new parameters to users/me endpoint

### ISSUE THREAD

**Issue by albullington** [inaturalist/iNaturalistAPI#216]
@kueda and I realized that `inatjs.users.me` does not currently return all necessary parameters to fill in the revamped User Settings pages. 

Here's a checklist of the parameters needed (with more to be added). The relevant Zeplin screens are linked for reference:

**[Profile & User page](https://zpl.io/bov64XZ)**
- [x] prefers_monthly_supporter_badge
- [x] description
- [x] updated_at

**[Account page](https://zpl.io/VDLejRv)**
- [x] time_zone
- [x] search_place_id

**[Content & Display page](https://zpl.io/bovjl7E)**
- [x] preferred_observation_license
- [x] preferred_photo_license
- [x] preferred_sound_license
- [x] preferred_project_addition_by
- [x] prefers_automatic_taxon_changes
- [x] prefers_community_taxa
- [x] preferred_observation_fields_by
- [ ] ~~make_observation_licenses_same~~
- [ ] ~~make_photo_licenses_same~~
- [ ] ~~make_sound_licenses_same~~

**[Notifications page](https://zpl.io/bPeodZp)**
- [x] prefers_receive_mentions
- [x] prefers_redundant_identification_notifications
- [x] prefers_no_email
- [x] prefers_comment_email_notification
- [x] prefers_identification_email_notification
- [x] prefers_mention_email_notification
- [x] prefers_message_email_notification
- [x] prefers_project_journal_post_email_notification
- [x] prefers_project_added_your_observation_email_notification
- [x] prefers_project_curator_change_email_notification
- [x] prefers_taxon_change_email_notification
- [x] prefers_user_observation_email_notification
- [x] prefers_taxon_or_place_observation_email_notification

**[Applications page](https://zpl.io/bzrGNr4)**
_- should iNat and external applications also be available through users.me? if so, probably need two attributes which return a list of app names, authorization date, and the application number for creating a delete link:_
- [ ] authorized_applications
- [ ] external_applications

**Comment by kueda** [comment]
FWIW, the following are not read attributes but ones you might set when updating the user to update the licenses on the user's content:

* make_observation_licenses_same
* make_photo_licenses_same
* make_sound_licenses_same

**Comment by albullington** [comment]
`prefers_automatic_taxonomic_changes` doesn't appear to be returning from users.me (and I noticed I used the wrong attribute name above -- should be taxonomic, not taxon). Everything else is looking good.

**Comment by kueda** [comment]
Pretty sure we're good here, please re-open if not. Handled `authorized_applications` in a separate endpoint.
