### ISSUE TITLE
Include default icon URL in users/me response

### ISSUE THREAD

**Issue by kueda** [inaturalist/iNaturalistAPI#224]
The question for me is whether it should be in `icon_url`, or somewhere else so the client knows when the user has chosen a profile pic and when they haven't. @budowski and @alexshepard, does that make any difference to you in the Android and iPhone apps?

**Comment by budowski** [comment]
On the Android side, this shouldn't make any difference for this endpoint.

**Comment by kueda** [comment]
I actually don't think this solves the original problem, which I think really concerns the fact that we inconsistently use `icon` and `icon_url` to mean the same thing in the API, and for users/me we're only including `icon`.
