### ISSUE TITLE
Undocumented place_id parameter in GET /projects

### ISSUE THREAD

**Issue by JWCook** [inaturalist/iNaturalistAPI#228]
I was trying to figure out how to get projects by place rather than lat/long/radius, since I noticed that the [Places page](https://www.inaturalist.org/places/) in the web app has a 'Projects' tab.

I found that `GET /projects` accepts a `place_id` parameter, although it's not listed in [the Swagger docs](https://api.inaturalist.org/v1/docs/#!/Projects/get_projects). Would you mind adding this to the docs for others' reference? Alternatively, is there another way to query projects by `place_id`?

Thanks!

**Comment by pleary** [comment]
I added place_id to the documentation for the projects search endpoint. That should be deployed later today. The only other way to search for projects by place is to use the "universal" search endpoint. The `place_id` param wasn't documented for that endpoint either, but I've added it and it will appear after the next deploy

**Comment by JWCook** [comment]
Thanks, Patrick!
