### ISSUE TITLE
Node API Requests

### ISSUE THREAD

**Issue by alexshepard** [inaturalist/iNaturalistAPI#23]
As part of my work to replace Reskit/CoreData with Mantle/Realm, I'd like to use the node API for pretty much everything in the app, so the transition sorta becomes RestKit/CoreData/Rails -> Mantle/Realm/Node.

__Really Kinda Need It__
- authenticated GET observations with private data fields
 - needed to show private coordinates
- UUIDs for uploadables
 - observations object needs a primary key
- GET /users/:id needs to return a full user object
 - needed to query user for # of obs & IDs for Me tab header
- Project and Site News Posts, the feed for logged in & anon users
 - needed to populate the News tab
- something like GET /users/new_updates.json
 - need a way to know what's new in for this user on the my observations tab
 - the red chatboxes on the Me tab
- a way to learn about server-side deletions 
 - like the "X-Deleted-Observations" header from rails

__Nice to have__

- GET /users/new_updates.json improvements
 - directly presentable information
  - i.e. "@kueda commented: 'get the fuck out!' on _your observation_"
  - or "@loarie identified _your observation_ as a stupid human"
  - this would allow us to show these updates in the news tab
- Comments, Identifications, and Faves in GET /observations? list view
 - to avoid re-fetching the observation for details view
- Full projects in observations
 - instead of just a list of Project IDs
 - to avoid having to make separate calls to get Project details

**Comment by pleary** [comment]
@alexshepard I see that the iOS app makes updates calls using `/users/new_updates.json?resource_type=Observation&skip_view=true&notifier_types=Identification%2CComment` and news calls using `posts/for_user.json?older_than=6044`. I'm wondering if for either of these endpoints you ever send other parameters. Any other notifier types for example? Or any parameters not listed here, like a page param or something?

**Comment by alexshepard** [comment]
We only query for those two notifier types because they're the only ones that are in the current iOS UI (we show the red chatbox on the Me tab with unseen content). If there are other things iOS could query for, I'd love to know.

For news posts, iOS also asks for `?newer_than=6044` We also query `/projects/:userid/journal.json` from the project details screen, which returns a list of project news.

**Comment by alexshepard** [comment]
In working on an old iOS bug, I remembered that projects sometimes have latitude, longitude, and place_id attached to them. It would be great if the project autocomplete API could return them, so we can draw overlays on the map.

Not sure if I should open a new issue for this?

**Comment by pleary** [comment]
@alexshepard I split this single ticket requesting an array of features into some individual tickets. The project lat/lng one is at #30 now. For other requests please add them to an appropriate existing ticket or make new ones. Thanks

**Comment by alexshepard** [comment]
👍

**Comment by pleary** [comment]
I've split this ticket up into individual features and I don't think it needs to stick around so I'm closing it. Pretty close to having it all done
