### ISSUE TITLE
GET /observations/identifiers maxes out at 500 records

### ISSUE THREAD

**Issue by willkuhn** [inaturalist/iNaturalistAPI#236]
# Rundown

* ``GET /observations/identifiers`` returns a maximum of 500 identifier records even if ``total_results`` is much higher
* empty pages are returned after the 500th record
* the final non-empty page contains ``500 % per_page`` records
* the fact that empty pages are returned after 500 makes it seem like there's a hard limit coded in here. Is that intentional? If so, it should probably be in the documentation
* the issue is probably around here: https://github.com/inaturalist/iNaturalistAPI/blob/main/lib/controllers/v1/observations_controller.js#L929-L953

# Examples

Here's an example for ``place_id=72645`` where ``total_results`` is around 2991.

With per_page=30 we get 16 pages (= 480 records) of expected results:
https://api.inaturalist.org/v1/observations/identifiers?place_id=72645&per_page=30&page=1
...
https://api.inaturalist.org/v1/observations/identifiers?place_id=72645&per_page=30&page=16

...then page 17 only returns 20 records (``= 500 % per_page``), instead of the expected 30:
https://api.inaturalist.org/v1/observations/identifiers?place_id=72645&per_page=30&page=17

Page 18 (record 501+) returns an empty page ```{"total_results":2991,"page":18,"per_page":30,"results":[]}```:
https://api.inaturalist.org/v1/observations/identifiers?place_id=72645&per_page=30&page=18

This seems to work the same regardless of the combination of ``per_page`` and ``page``.

Other large queries (>500 records) behave the same, but smaller queries return all results as expected. For example:
https://api.inaturalist.org/v1/observations/identifiers?place_id=11&iconic_taxa=Protozoa&per_page=50&page=1

**Comment by pleary** [comment]
The observers and identifiers queries can be computationally intensive to process, and the intention was to limit these endpoints to a maximum of 500 results. Seems like that was working properly for identifiers but not observers. I think I fixed the issue with observers and now it should behave the same as identifiers (after the next deploy). I also added to the documentation that only 500 results can be returned
