### ISSUE TITLE
Mysterious lack of vision results

### ISSUE THREAD

**Issue by kueda** [inaturalist/iNaturalistAPI#241]
When using the taxon autocomplete component at https://www.inaturalist.org/observations/69740400, you get no results, as in the API call like

```
curl 'https://api.inaturalist.org/v1/computervision/score_observation/69740400' \
  -H 'Accept: application/json' \
  -H 'Authorization: MY_JWT'
```

returns `{"total_results":0,"page":1,"per_page":0,"results":[]}`. The photo file doesn't seem weird, other attributes of the observation seem normal. Not sure what's going on.

**Comment by pleary** [comment]
I couldn't replicate a lack of results for this observation. Please reopen if there are other observations showing the same problem
