### ISSUE TITLE
GET /controlled_terms/for_taxon returns 422 instead of 404 if the taxon does not exist

### ISSUE THREAD

**Issue by JWCook** [inaturalist/iNaturalistAPI#258]
This likely isn't important at all, but I'm adding this for reference since this looks like unintended behavior.

Example request:
```bash
$ curl --header 'Accept: application/json' 'https://api.inaturalist.org/v1/controlled_terms/for_taxon?taxon_id=99999999'
{"error":"Error","status":422}
```

**Comment by pleary** [comment]
This is intended and I believe appropriate. I don't think a 404 should be used if the target endpoint (`v1/controlled_terms/for_taxon`) exists and is available. In this case the endpoint does exist, but it's the parameter that is causing a problem. A 422 `indicates that the server understands the content type of the request entity, and the syntax of the request entity is correct, but it was unable to process the contained instructions`, which I think is the case here. It's also consistent with how Ruby on Rails handles this type of issue, which we use for the main website, so I think it makes sense for a little consistency between the rails website and node.js API.

So I'll close this, but feel free to re-open with an argument for changing it if you disagree

**Comment by JWCook** [comment]
Thanks for the info! I wasn't familiar with that convention in Rails, but that makes sense.
