### ISSUE TITLE
something like GET /users/new_updates.json

### ISSUE THREAD

**Issue by pleary** [inaturalist/iNaturalistAPI#26]
```
- need a way to know what's new in for this user on the my observations tab
- the red chatboxes on the Me tab
```

and "nice to have"
```
- directly presentable information
  - i.e. "@kueda commented: 'get the fuck out!' on your observation"
    or "@loarie identified your observation as a stupid human"
  - this would allow us to show these updates in the news tab
```
Requested in uber ticket #23

**Comment by pleary** [comment]
@alexshepard I made http://staging.inaturalist.org:8080/v1/observations/updates which only returns updates on obs for the currently authenticated user. If there is no authentication header, it'll return an HTTP error 401 unauthenticated. I have it returning IDs and comments on the authenticated users obs, and it will include the actual ID or comment (but not the obs since you should have that cached from the user's me tab). Will that work?

**Comment by alexshepard** [comment]
Yep, I think that should work great. Based on this, I can start working on background fetch -> local notifications when new activity happens on your observations. Yay!
