### ISSUE TITLE
Questions about client-side rate-limiting

### ISSUE THREAD

**Issue by JWCook** [inaturalist/iNaturalistAPI#265]
For [pyinaturalist](https://github.com/niconoe/pyinaturalist), a couple versions ago I added rate-limiting by default to stay within the limits described in [API Recommended Practices](https://www.inaturalist.org/pages/api+recommended+practices#query-rate) (1/second, 60/minute, 10K/day), using a leaky bucket rate-limiter.

A user has a case where they need to make a few small requests in quick succession to display results in real time (for the unofficial iNat Discord server). They would like to be able to exceed the per-second limit in short bursts, but still average out to a rate under the per-minute limit. Do you have any guidelines for what a reasonable burst rate limit would be? For example, something like 5 requests per 5 seconds (5 consecutive requests followed by a delay of up to 5 seconds), or 10 requests per 10 seconds, etc.? And is there a server-side per-second rate limit?

In general, do you have any other suggestions for client-side features to discourage the kinds of usage patterns you don't want to see (like scraping)? At @pleary's [request](https://github.com/niconoe/pyinaturalist/issues/8) we added a custom User-Agent (`pyinaturalist/$version`) about 2 years ago, so I'd be curious to see what kinds of metrics you have on its usage.

**Comment by pleary** [comment]
There is no per-second limit on the server-side - the smallest enforced limit is on the per-minute scale. So if a user needed to make 60 requests very quickly they could, but would then need to wait about a minute before making any more requests. Obviously if the requests were all computationally heavy, it may put a bust of pressure on the backend which could lead to longer response times. So it would probably be more ideal for us if 60 requests were spread out over a minute, but we don't prevent them from happening quickly, nor is there any official recommendations about that.

> In general, do you have any other suggestions for client-side features to discourage the kinds of usage patterns you don't want to see (like scraping)?

I think we've covered the main recommendations in the page you linked to on [API Recommended Practices](https://www.inaturalist.org/pages/api+recommended+practices#query-rate). People shouldn't be using the API for scraping data at all, and should rather use observation exports or using pre-generated datasets like the archive we provide to GBIF (or using GBIF's search and export features).

> so I'd be curious to see what kinds of metrics you have on its usage.

We have pretty good data on API usage in a one month rolling window. Is there anything in particular you're looking for?

**Comment by JWCook** [comment]
> People shouldn't be using the API for scraping data at all

Yes, I understand. As a science-adjacent backend dev (day job) and a fan of iNaturalist, I'm trying to make sure my API client plays nice with the API.

> Is there anything in particular you're looking for?

I'd be interested in:
* Distribution of response status codes: If, for example, there were a significant amount of 4xx errors, that might indicate a bug in pyinaturalist
* Distribution of HTTP methods: I'm curious if usage is mostly read-only, or if creating/updating observations is common
* Ballpark idea of the total number of requests in the last month

Thanks!

**Comment by pleary** [comment]
> Yes, I understand. As a science-adjacent backend dev (day job) and a fan of iNaturalist, I'm trying to make sure my API client plays nice with the API.

Thanks - it is much appreciated. I'd say the best we can ask for is for clients to stick by the guidelines, and if we see issues arise and we need to tweak guidelines, we will do so. We don't want to be too heavy handed - just enough that a small subset of users aren't able to disrupt the experience of other users, and recently things have been going smoothly.

> Distribution of response status codes: If, for example, there were a significant amount of 4xx errors, that might indicate a bug in pyinaturalist

Here's some data over the last 30 days. I'm seeing overwhelmingly 200 respond codes:

<img width="476" src="https://user-images.githubusercontent.com/48566/128387784-587e3374-8c97-4dd8-973e-d6ed85c9eae6.png">

> Distribution of HTTP methods: I'm curious if usage is mostly read-only, or if creating/updating observations is common

<img width="463" src="https://user-images.githubusercontent.com/48566/128387816-344dca26-a64d-4930-96e6-90b871c51b3d.png">

> Ballpark idea of the total number of requests in the last month

As you can see in the above charts I'm seeing about 250k requests with a pyinaturalist user agent over the last 30 days. 

Another interesting chart is aggregating request counts by client IPs (obfuscated for privacy). There's clearly one heavy user that is a borderline scraper. They're fetching obs one at a time. Maybe I'll reach our to them. Then there's a couple other bigger users then a long tail: 

<img width="463" src="https://user-images.githubusercontent.com/48566/128388168-ff5e804e-17eb-4ce7-b5d0-5bf1e2dde5b7.png">

**Comment by JWCook** [comment]
Interesting, thanks for pulling that info for me! Even excluding the top user, that's more usage than I was expecting.

If you do contact User A, they're welcome to ping me (or ask on the forums) for help on getting that data more efficiently. If it's for data analysis, I'm working on some [tools](https://github.com/JWCook/pyinaturalist-convert) to make it easier to convert and combine data from the API, CSV export tool, eventually the DwC archive, and possibly the observation metadata from the iNaturalist Open Dataset.

Or if it's for an application, I've also been working on a [caching library](https://github.com/reclosedev/requests-cache) to help avoid repeat queries (especially for infrequently-changing data like taxa).

I think that answers all my questions for now, so I'll go ahead and close this. Thanks!
