### ISSUE TITLE
add params for acc_below=x OR acc=false

### ISSUE THREAD

**Issue by loarie** [inaturalist/iNaturalistAPI#274]
Several use cases, e.g. existing marked atlas functionality and the activities discussed here
https://www.inaturalist.org/blog/44732-exploring-fine-scale-geographic-patterns-on-inaturalist
would benefit from the ability to exclude observation that aren't precise OR have an unknown precision.

Currently `acc_below` behaves as `acc_below=X` AND `acc=true` so can't be used for the above application

To avoid changing the meaning of the `acc_below` param, this request is to add new params hat behave as `acc_below=X` OR `acc=false`

**Comment by bianav** [comment]
Working on this.

**Comment by kueda** [comment]
Closed in https://github.com/inaturalist/iNaturalistAPI/pull/278
