### ISSUE TITLE
Comments, Identifications, and Faves in GET /observations? list view

### ISSUE THREAD

**Issue by pleary** [inaturalist/iNaturalistAPI#28]
`to avoid re-fetching the observation for details view`

Requested in uber ticket #23

**Comment by pleary** [comment]
You can now everything from search you would get in /observations/ID by adding ?details=all to the search request, http://staging.inaturalist.org:8080/v1/observations?details=all . Will that work for you?

**Comment by alexshepard** [comment]
That looks great, thanks @pleary
