### ISSUE TITLE
Universal search does not get an exact match for "treehu"

### ISSUE THREAD

**Issue by kueda** [inaturalist/iNaturalistAPI#280]
https://api.inaturalist.org/v1/search?sources=users&q=treehu does not show https://www.inaturalist.org/people/treehu as the first results (or in the first 10 results) even though the username is an exact match. Exact matches should always appear at the top of results.

**Comment by pleary** [comment]
I boosted exact matches for usernames which puts the user at the top for this search now. They may not necessarily be first, so please reopen if other cases come up. Not deployed to production yet
