### ISSUE TITLE
Support /projects endpoints in API v2

### ISSUE THREAD

**Issue by albullington** [inaturalist/iNaturalistAPI#282]
For iNatRN, we need to be able to display a search box for projects, a list of projects a user has joined, a list of featured projects, and a list of nearby projects.

A user should be able to tap into a specific project and leave/join, see project news, and see details about the project.

- [x]  GET /projects/search
- [x]  GET /projects/:id
- [x]  POST /projects/:id/join
- [x]  DELETE /projects/:id/leave

Related to [this issue](https://github.com/inaturalist/iNaturalistReactNative/issues/8) in the iNatRN repo.

**Comment by pleary** [comment]
* search is at GET `/projects`
* join is at POST `/projects/{id}/membership`
* leave is at DELETE `/projects/{id}/membership`
