### ISSUE TITLE
Add /search endpoint to API v2

### ISSUE THREAD

**Issue by albullington** [inaturalist/iNaturalistAPI#283]
For the iNat mobile redesign, we'll need a `/search` endpoint that works like header search on the web. End users should be able to query and receive taxa + user results.

The endpoint should also support API v2.

Related to [this issue](https://github.com/inaturalist/iNaturalistReactNative/issues/9) in iNaturalistReactNative.

**Comment by pleary** [comment]
v2 now has a search endpoint. The results aren't fully described - we may want to try to get OpenAPI discriminators working properly, or resort to using different attributes to represent the different types of records that could be returned. But for now there's a version that will at least return results
