### ISSUE TITLE
Add /identifications/similar_species to API v2

### ISSUE THREAD

**Issue by albullington** [inaturalist/iNaturalistAPI#286]
For iNatRN, we'll need to display results from the identifications/similar_species endpoint, similar to Taxon Details on the web.

- [x] GET /identifications/similar_species

**Comment by kueda** [comment]
@abhasinat can we live without this? @pleary can correct me if I'm wrong, but that endpoint is a bit of a performance liability, so it might be worth avoiding in the new mobile app.

**Comment by pleary** [comment]
I added the endpoint since we may want it for other places. It is indeed a pretty heavy query to run, so ideally we'd avoid it in new interfaces, or bury it so it requires user action each time it gets called. It's also only usable on taxa of rank genus or below
