### ISSUE TITLE
GET /projects needs a fields parameter for API v2

### ISSUE THREAD

**Issue by albullington** [inaturalist/iNaturalistAPI#290]
We should be able to return a project title and icon via the fields parameter from GET /projects.

**Comment by pleary** [comment]
This seems to be working for me, e.g. https://api.inaturalist.org/v2/projects/558?fields=title,icon . If you're getting an error could you please include the URL/request?

**Comment by kueda** [comment]
Ah, sorry @pleary, I think Amanda and I discussed this and I think the bug might have been when `fields` is in the body of a POST request, not in the query of a GET request, though I didn't try and replicate it.

**Comment by pleary** [comment]
OK - fwiw I tried that too and that also appears to work for me

```bash
curl -XPOST \
     -H "X-HTTP-Method-Override: GET" \
     -H "Content-Type: application/json" \
     -d '{"fields": {"title": true, "icon": true}}' \
     "https://api.inaturalist.org/v2/projects/558"
```
```json
{"total_results":1,"page":1,"per_page":1,"results":[{"id":558,"title":"Vermont Atlas of Life","icon":"https://static.inaturalist.org/projects/558-icon-span2.jpg?1505453933"}]}
```

**Comment by kueda** [comment]
Ah. @albullington, can you replicate this and if so clarify the repro conditions, and if not close?
