### ISSUE TITLE
/projects/{id} returning 500 error in API v2

### ISSUE THREAD

**Issue by albullington** [inaturalist/iNaturalistAPI#293]
Fetching a project by an integer via GET /projects/{id} is currently returning a middleware error ([example](https://api.inaturalist.org/v2/projects/54866)), and fetching by project slug ([same example project](https://api.inaturalist.org/v2/projects/lgbtq-naturalists)) is no longer supported in v2.

**Comment by kueda** [comment]
This is kind of by design. Is there some place where you're not receiving a project UUID?

**Comment by albullington** [comment]
Is this supposed to take a regular id or a uuid? It looks like a uuid is also not supported since this is expecting an integer, at least when I try to test it out [here](https://api.inaturalist.org/v2/docs/#/Projects/get_projects__id_). Is there another way I can fetch a single project?

**Comment by kueda** [comment]
Ah, sorry, I was wrong. I think this *should* take a serial ID, there's just a bug.
