### ISSUE TITLE
'preferred_common_name' not retrieved for Hebrew  

### ISSUE THREAD

**Issue by tom-gu** [inaturalist/iNaturalistAPI#297]
Locale preference for taxon common names is not working for Hebrew:
GET /taxa/autocomplete | q = Gyps fulvus | rank = species | **locale = he** | all_names = true |
https://api.inaturalist.org/v1/taxa/autocomplete?q=Gyps%20fulvus&rank=species&locale=he&all_names=true

Common Hebrew name exists:
![image](https://user-images.githubusercontent.com/16609623/152438995-b2a8a99a-c9b6-4d32-8fbd-415c6f6ac217.png)
'preferred_common_name' was not retrieved:
![image](https://user-images.githubusercontent.com/16609623/152439094-1b9cf63c-d64c-4dfe-83cb-8c7fc1f70c43.png)

**"iw" (old-style locale for Hebrew) is also not working
https://github.com/inaturalist/iNaturalistAPI/blob/aa6514218d2828263c00022e19e115f3ce39ba6c/lib/util.js#L91-L96

Works fine for all existing locals. Example  for Arabic:
GET /taxa/autocomplete | q = Gyps fulvus | rank = species | **locale = ar** | all_names = true |
https://api.inaturalist.org/v1/taxa/autocomplete?q=Gyps%20fulvus&rank=species&locale=ar&all_names=true
![image](https://user-images.githubusercontent.com/16609623/152439445-4011cc79-239d-4d7b-b1ed-832df04b06ca.png)
![image](https://user-images.githubusercontent.com/16609623/152439487-c2240097-908c-4d70-b67b-bcbfed380f31.png)

**Comment by kueda** [comment]
Thanks for the report, @tom-gu. The examples you provided are working for me after deploying the above change.

**Comment by tom-gu** [comment]
Thank you @kueda for fixing it so quickly :bowtie:
