### ISSUE TITLE
Update API docs regarding image URLs

### ISSUE THREAD

**Issue by kueda** [inaturalist/iNaturalistAPI#299]
The API docs describe fields like `large_url` and `medium_url` that don't actually get returned. We should note some things like 

1. How to retrieve different sizes given the `url` attribute that is always the `square` URL by default
2. Point people toward https://github.com/inaturalist/inaturalist-open-data/ if they're interested in image data
3. Point out that not all sizes are available for all images (or are they?)
4. Note that domains are not necessarily stable b/c images will change buckets if they are licensed or unlicensed.

**Comment by npdoty** [comment]
Also, it seems like extensions aren't always the same (for example, some `.jpeg` and some `.jpg` which aren't interchangeable) and no extension is guaranteed.
