### ISSUE TITLE
How to filter api search for observations which do NOT have ANY phenological annotations?

### ISSUE THREAD

**Issue by abubelinha** [inaturalist/iNaturalistAPI#311]
I am looking at the observations api documentation but I couldn't find a way to do this.
Looking to #77 it seems to be possible using `without_term_value_id`, but actually it doesn't work the way I need.

With that option, you can find something which is not annotated as "flowering" ... but it may be annotated as "fruiting", or "budding" or "not flowering". 
Even if I combine all possible values in the array (`term_id=12&without_term_value_id=[13,14,15,21]`), I just will find observations which do not have ONE or SOME of those annotations (but may have none, one or some of the others present in the array). 

It's much more useful finding out observations which still haven't ANY phenological annotations ... so I can annotate them and improve data. 
How should I construct the query to do that?

Thanks

**Comment by kueda** [comment]
Please use https://forum.inaturalist.org to ask questions about how to use the API. We use github to organize and coordinate changes to our software.

FWIW, I don't believe we currently have a way to use the API to find observations with no annotations at all.

**Comment by kueda** [comment]
We prefer that feature requests go through the Forum as well. For a general guide to contributing to iNat via github, check out https://github.com/inaturalist/inaturalist/blob/main/CONTRIBUTING.md

**Comment by abubelinha** [comment]
I see. Sorry about having posted it here.
