### ISSUE TITLE
Support POST /v2/photos

### ISSUE THREAD

**Issue by kueda** [inaturalist/iNaturalistAPI#319]
This will allow us to upload photos before creating an observation, which is how we do it in the Uploader on the web.

**Comment by pleary** [comment]
This is available now. I also added PUT /v2/photos/:id since we have that in v1 and it looks like the Android app uses it - but we can remove that if it's unnecessary

**Comment by kueda** [comment]
I don't think we need PUT /v2/photos/:id right now, but we will if we're shooting for parity with the web, or if we ever want to update individual media licenses in React, so it's good to have.
