### ISSUE TITLE
Include UUIDs in response to /v2/observations/updates

### ISSUE THREAD

**Issue by kueda** [inaturalist/iNaturalistAPI#329]
Currently we return `resource_type` and `resource_id` but not a UUID if available. Ideally I'd like to see the `uuid` version of every `id` in this response, but I think we can do what we need to do in iNat mobile if we just get a `resource_uuid` attribute that contains the UUID of the resource (in this case they should all be observations). Probably involves some Rails work.

For context, the iNat React Native app needs to fetch updates, but since it mostly uses API v2, it largely relies on the UUID as the observation's unique identifier, including in its local database. We can work with the sequential `id`, but I think it would be preferable to show `uuid` along with id whenever we can in v2.

**Comment by pleary** [comment]
I added `resource_uuid` to the response. Comment and ID UUIDs are in their respective objects
