### ISSUE TITLE
Specify what request params trigger errors in v2

### ISSUE THREAD

**Issue by kueda** [inaturalist/iNaturalistAPI#331]
A request like PUT `/v2/users/:id` might yield an error response with a body like this: 

```json
{
    "errors":
    [
        {
            "errorCode": "additionalProperties.openapi.requestValidation",
            "location": "body",
            "message": "must NOT have additional properties"
        }
    ],
    "status": 400
}
```

This isn't super helpful because you don't know what parameters were the additional ones that triggered the error. Patrick suggests that's it may be possible to write a custom `errorTransformer` to provide a more helpful error message that describes exactly which parameters were extraneous.

Additionally, it would be great if the status was 422 in cases were the client specified parameters incorrectly. 400 could mean anything.

**Comment by pleary** [comment]
This should be resolved now. We should be indicating the attribute name and location for input objects that are missing properties or have unexpected properties, and same for responses
