### ISSUE TITLE
Add application field to observations/search

### ISSUE THREAD

**Issue by albullington** [inaturalist/iNaturalistAPI#354]
I tried setting fields to include `application: { name: true }`, and it looks like this is currently not being returned from observations/search. However, it is being returned by observations/fetch.

**Comment by pleary** [comment]
This should work now for `application` in obs/search. That's an attribute that we never return in v1 for search w/o using the `?details=all` param, but I added the ability to include it in v2 if requested. There will be other attributes that behave the same way and we can eventually add the same logic for those, or change the documentation in v2 for search to indicate they can't be returned. Ideally any attribute could be requested and would be fetched on-demand in v2, we just haven't gotten there yet unfortunately
