### ISSUE TITLE
Support GET observations/deleted in API v2

### ISSUE THREAD

**Issue by albullington** [inaturalist/iNaturalistAPI#355]
For iNatRN, we'll need this API endpoint to fetch recent deletions from the server and update a user's local observation list accordingly. (We'll also need this endpoint enabled in the inaturalistjs library).

**Comment by pleary** [comment]
This should be all set with 1f82728 and https://github.com/inaturalist/inaturalistjs/commit/26be1e49e82127182f629be9af8ac2a5a89df576 and will return observation integer IDs as that is all we have in the `deleted_observations` table. If you'll need UUIDs let me know and I'll make a ticket to add that column and update the response when the data is available. We'd only be able to get UUIDs of obs deleted after we run that migration
