### ISSUE TITLE
histograms endpoint

### ISSUE THREAD

**Issue by kueda** [inaturalist/iNaturalistAPI#36]
Part of the way at https://github.com/inaturalist/iNaturalistAPI/commits/histograms. Requirements are:

- [x] ability to get counts of observations grouped by month
- [x] ability to get counts of observations grouped by year-month

Would be nice to specify the kind of grouping for both of these. Though Patrick's current approach of showing numerous groupings at once could also work.

**Comment by pleary** [comment]
I put the working version on staging, see http://staging.inaturalist.org:8080/v1/docs/#!/Observations/get_observations_histogram . It accepts all the obs search parameters as well as `date_field` and `interval`. It can do things like:
- Observations grouped by month of year observed http://staging.inaturalist.org:8080/v1/observations/histogram?date_field=observed&interval=month_of_year
- Observations of birds grouped by year created http://staging.inaturalist.org:8080/v1/observations/histogram?date_field=created&interval=year&taxon_id=3

`date_field` can be `created` or `observed` (default), and interval can be `year`, `month`, `week`, `day`, `month_of_year` (default), `week_of_year`, and `day_of_month`. I also set default `d1` or `created_d1` valued (depending on the value of `date_field`) to limit the number of buckets returned for `year` and `month` (100 years), `week` (10 years), and day (1 year), which can be overridden.
