### ISSUE TITLE
Allow users to search by ORCID

### ISSUE THREAD

**Issue by tiwane** [inaturalist/iNaturalistAPI#372]
From https://forum.inaturalist.org/t/search-users-by-orcid/37362

Add ORCID to the search API so users can be find using their ORCID.

**Comment by kueda** [comment]
@OrigamiBurger is working on this in https://github.com/inaturalist/iNaturalistAPI/pull/393, just can't assign them until they comment here, I think.

**Comment by pleary** [comment]
This was resolved by @OrigamiBurger in #393
