### ISSUE TITLE
Add iconic filter to /taxa

### ISSUE THREAD

**Issue by kueda** [inaturalist/iNaturalistAPI#390]
In order to build an iconic taxon chooser in the mobile app, we need to fetch the iconic taxa. IMO, something like `/v2/taxa?iconic=true` would do the trick, though a separate endpoint like `/v2/taxa/iconic` would be fine too.

**Comment by pleary** [comment]
I added both options. There is now e.g. https://api.inaturalist.org/v2/taxa/iconic?fields=name which returns all iconic and doesn't accept other parameters. The search endpoint also accepts an iconic parameter e.g. https://api.inaturalist.org/v2/taxa?iconic=true&fields=name
