### ISSUE TITLE
POST /v1/annotations does not set user.last_ip correctly in Rails app

### ISSUE THREAD

**Issue by kueda** [inaturalist/iNaturalistAPI#417]
Not sure which repo to put this in, but I suspect the change needs to happen here or in inaturalistjs.

Repro steps:

1. Verify that a test user's `last_ip` is set to something other than a 10.x.x.x address (e.g. from console or admin tool)
1. Using a JWT for that test user, run this request (you'll probably want to replace the resource_id with a test observation of a flowering plant):
    ```zsh
    curl 'https://api.inaturalist.org/v1/annotations' \
      -X POST \
      -H 'Authorization: TEST-USER-JWT' \
      --data-raw '{"resource_type":"Observation","resource_id":193080589,"controlled_attribute_id":12,"controlled_value_id":21}'
    ```
1. The user's `last_ip` value is now a 10.x.x.x address

I'm guessing the problem might be restrcited to POST requests, or maybe just annotations, but the above steps work consistently for me. The expectation is that `last_ip` gets set to the actual IP of the end user, not one of our internal server IPs.

**Comment by sylvain-morin** [comment]
See: https://github.com/inaturalist/inaturalist/pull/4023
