### ISSUE TITLE
Additions to /observations/updates

### ISSUE THREAD

**Issue by alexshepard** [inaturalist/iNaturalistAPI#43]
In order to show a feed of updates in the iOS app, we'll need to start being able to request all updates on my content, not just new updates. It would be great to see:
- `/observations/updates` returns all updates on my content
- `/observations/updates` accepts some kind of `created_after` (either a date or another update id) parameter
- `/observations/updates` returns a `viewed` boolean indicating whether the user has seen this update or not (useful for making notifications and other UI stuff)

**Comment by alexshepard** [comment]
this is looking great.

one thing I'm noticing is that the user objects that are coming back as part of the identifications/comments inside the update don't have icon urls. Is this something that can be added?

**Comment by alexshepard** [comment]
Another thing, very minor, is that dates for updates are coming in with microseconds like `2016-10-09T20:37:31.770-07:00`, whereas other dates from the node api don't seem to. It's not a big deal for me to make a different datetime formatter for updates, just letting you know in case it was an oversight.

**Comment by pleary** [comment]
both the user icon metadata and date formatting should be fixed now
