### ISSUE TITLE
response must have required property total_results and page

### ISSUE THREAD

**Issue by kueda** [inaturalist/iNaturalistAPI#458]
When https://www.inaturalist.org/people/7999426 requests https://api.inaturalist.org/v2/observations?verifiable=true&lat=31.711277319147914&lng=-110.65551954331869&radius=50&order_by=created_at&order=desc&quality_grade=research&quality_grade=needs_id&per_page=20&fields=(comments%3A(current%3A!t)%2Ccreated_at%3A!t%2Cgeojson%3A!t%2Cgeoprivacy%3A!t%2Cid%3A!t%2Cidentifications%3A(current%3A!t)%2Clatitude%3A!t%2Clongitude%3A!t%2Cobscured%3A!t%2Cobservation_photos%3A(id%3A!t%2Cphoto%3A(attribution%3A!t%2Cid%3A!t%2Clicense_code%3A!t%2Curl%3A!t)%2Cposition%3A!t%2Cuuid%3A!t)%2Cobservation_sounds%3A(id%3A!t)%2Cplace_guess%3A!t%2Cquality_grade%3A!t%2Ctaxon%3A(iconic_taxon_name%3A!t%2Cis_active%3A!t%2Cname%3A!t%2Cpreferred_common_name%3A!t%2Crank%3A!t%2Crank_level%3A!t)%2Ctaxon_geoprivacy%3A!t%2Ctime_observed_at%3A!t)&ttl=-1&page=1&return_bounds=true

I'm seeing this error in the logs

```
{
    "status": "500",
    "errors":
    [
        {
            "errorCode": "500",
            "message": "Invalid response for status code 200: response: must have required property 'total_results',response: must have required property 'page',response: must have required property 'per_page',response: must have required property 'results',response: must NOT have additional properties,response: must NOT have additional properties,response: must NOT have additional properties,response: must NOT have additional properties,response: must NOT have additional properties"
        }
    ]
}
```

I don't see the same when I make the same request, so I'm a bit confused. Here's the [relevant part of the logs](https://kibana-vpn.inaturalist.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2024-09-14T10:43:22.761Z',to:'2024-09-14T18:25:07.239Z'))&_a=(columns:!(error_message,url,status_code),filters:!(('$state':(store:appState),meta:(alias:!n,disabled:!f,index:'0bcbeff0-ec31-11ec-98e3-27373d6fb04e',key:x_installation_id,negate:!f,params:(query:'5e15a82b-04d4-40d1-83d3-3dc0693c3711'),type:phrase),query:(match_phrase:(x_installation_id:'5e15a82b-04d4-40d1-83d3-3dc0693c3711')))),index:'0bcbeff0-ec31-11ec-98e3-27373d6fb04e',interval:auto,query:(language:kuery,query:'parsed_user_agent.name:iNaturalistReactNative'),sort:!(!('@timestamp',desc)))).

FWIW, this is currently one of our top errors in iNat Next.

**Comment by pleary** [comment]
I suspect these errors were related to v2 caching issues in between deploying 7f169fdae9056e00829ef4e89b6616f997d1d9dc and b8216e704d580f30d240920873cfac280e91f93a. I can't say exactly what they were hitting during that time, but the errors appear isolated to those days and don't appear to have happened since. I cannot currently replicate. I'll close this issue, but please reopen if these errors occur again
