### ISSUE TITLE
Add obs search param to include only observations with obscured coordinates

### ISSUE THREAD

**Issue by kueda** [inaturalist/iNaturalistAPI#472]
This came up as I was trying to advise a partner on how best to ingest data using the API: we support geoprivacy=obscured,private and taxon_geoprivacy=obscured,private, but we have no param that just includes observations that are obscured for any reason. In that vein, I think it would be useful to support

- [x] `obscuration=obscured`: include observations where the coordinates have been obscured (not private), i.e. geoprivacy == 'obscured' OR taxon_geoprivacy == 'obscured
- [x] `obscuration=private`: include observations where the coordinates are private, i.e. geoprivacy == 'private' OR geoprivacy == 'private`
- [x] `obscuration=any` (or maybe `obscuration=obscured,private` to match the geoprivacy params): include observations that are obscured OR private for any reason
- [x] `obscuration=none`: include observations that have no obscuration, so not obscured or private

**Comment by pleary** [comment]
An `obscuration` parameter has been added. I went with the `obscuration=obscured,private` option. Setting the parameter to just `none` should be equivalent to setting `geoprivacy=open&taxon_geoprivacy=open`
