### ISSUE TITLE
shorten 'not in complete set' URL

### ISSUE THREAD

**Issue by loarie** [inaturalist/iNaturalistAPI#54]
I've included this link to observations within a taxon/place not represented in a complete set
https://github.com/inaturalist/inaturalist/blob/master/app/views/complete_sets/show.html.haml#L10

but while very long URLs like this work in the AP, e.g. http://api.inaturalist.org/v1/observations?hrank=species&lrank=species&place_id=1&taxon_id=40151&verifiable=true&without_taxon_id=40323%2C40325%2C40342%2C40343%2C40344%2C40345%2C40346%2C40347%2C40348%2C40349%2C40350%2C40352%2C40354%2C40509%2C40520%2C40521%2C40522%2C40523%2C40526%2C40527%2C40569%2C40614%2C40621%2C40629%2C40631%2C41143%2C41144%2C41147%2C41180%2C41182%2C41224%2C41276%2C41277%2C41301%2C41314%2C41315%2C41403%2C41406%2C41407%2C41408%2C41410%2C41411%2C41413%2C41414%2C41418%2C41421%2C41426%2C41428%2C41440%2C41446%2C41461%2C41464%2C41465%2C41478%2C41482%2C41494%2C41495%2C41496%2C41500%2C41503%2C41505%2C41509%2C41510%2C41521%2C41523%2C41525%2C41526%2C41529%2C41532%2C41534%2C41537%2C41539%2C41541%2C41543%2C41545%2C41550%2C41553%2C41558%2C41559%2C41562%2C41566%2C41569%2C41570%2C41638%2C41641%2C41644%2C41663%2C41673%2C41676%2C41691%2C41698%2C41702%2C41706%2C41708%2C41714%2C41728%2C41733%2C41740%2C41746%2C41755%2C41757%2C41766%2C41777%2C41789%2C41798%2C41799%2C41808%2C41809%2C41810%2C41815%2C41852%2C41860%2C41877%2C41879%2C41880%2C41882%2C41901%2C41970%2C41974%2C41976%2C41997%2C42007%2C42048%2C42051%2C42052%2C42066%2C42069%2C42070%2C42076%2C42077%2C42113%2C42122%2C42134%2C42161%2C42166%2C42199%2C42206%2C42210%2C42220%2C42223%2C42308%2C42310%2C42390%2C42391%2C42408%2C42412%2C42414%2C42416%2C42422%2C42426%2C42429%2C42652%2C42937%2C43101%2C43102%2C43108%2C43109%2C43110%2C43111%2C43112%2C43115%2C43116%2C43127%2C43128%2C43129%2C43130%2C43131%2C43132%2C43145%2C43149%2C43151%2C43188%2C43197%2C43335%2C43460%2C43736%2C43794%2C43840%2C43844%2C43846%2C43848%2C43997%2C44026%2C44053%2C44054%2C44055%2C44057%2C44058%2C44059%2C44060%2C44062%2C44063%2C44064%2C44065%2C44066%2C44067%2C44068%2C44069%2C44070%2C44088%2C44089%2C44090%2C44091%2C44092%2C44093%2C44094%2C44095%2C44096%2C44097%2C44104%2C44105%2C44106%2C44107%2C44110%2C44114%2C44115%2C44116%2C44117%2C44120%2C44121%2C44124%2C44125%2C44126%2C44129%2C44132%2C44148%2C44149%2C44150%2C44151%2C44154%2C44155%2C44156%2C44160%2C44162%2C44163%2C44298%2C44300%2C44306%2C44307%2C44311%2C44315%2C44316%2C44317%2C44318%2C44319%2C44323%2C44324%2C44325%2C44326%2C44329%2C44332%2C44333%2C44378%2C44387%2C44388%2C44390%2C44391%2C44392%2C44393%2C44394%2C44395%2C44396%2C44397%2C44398%2C44399%2C44414%2C44415%2C44416%2C44431%2C44432%2C44433%2C44434%2C44437%2C44469%2C44470%2C44574%2C44575%2C44576%2C44705%2C44744%2C44747%2C44748%2C44749%2C44757%2C44758%2C44759%2C44760%2C44761%2C44762%2C44899%2C44902%2C44904%2C44905%2C45044%2C45687%2C45689%2C45691%2C45708%2C45709%2C45710%2C45712%2C45714%2C45715%2C45717%2C45719%2C45720%2C45721%2C45758%2C45760%2C45761%2C45763%2C45820%2C46009%2C46017%2C46018%2C46019%2C46020%2C46023%2C46024%2C46086%2C46087%2C46092%2C46093%2C46095%2C46177%2C46178%2C46179%2C46180%2C46213%2C46215%2C46216%2C46217%2C46218%2C46219%2C46220%2C46221%2C46222%2C46225%2C46226%2C46227%2C46228%2C46229%2C46230%2C46231%2C46232%2C46233%2C46234%2C46235%2C46236%2C46237%2C46253%2C46254%2C46255%2C46256%2C46259%2C46260%2C46266%2C46272%2C46309%2C46316%2C46348%2C46352%2C46355%2C46365%2C46366%2C46368%2C46377%2C46403%2C46407%2C46415%2C46416%2C46418%2C46430%2C46433%2C46436%2C46437%2C46438%2C46445%2C46446%2C46456%2C46477%2C46487%2C46488%2C46491%2C46500%2C46503%2C46509%2C46510%2C46841%2C46883%2C46886%2C46915%2C46918%2C46994%2C47007%2C47010%2C47014%2C47049%2C47051%2C47056%2C47075%2C58393%2C59815%2C63113%2C64102%2C68093%2C74048%2C74103%2C74173%2C74204%2C74205%2C74207%2C74328%2C74359%2C74476%2C74478%2C74675%2C74677%2C74681%2C74712%2C74715%2C74719%2C74756%2C74757%2C74758%2C74824%2C74852%2C74855%2C74890%2C75053%2C75088%2C75113%2C118552%2C123070%2C148030%2C179937%2C179987%2C179988%2C179990%2C179992%2C179993%2C179994%2C179995%2C179996%2C179997%2C179998%2C179999%2C180000%2C180001%2C180002%2C180003%2C180005%2C180007%2C180008%2C180009%2C180010%2C183164%2C183166%2C197781%2C209233%2C233598%2C446640%2C520561

they don't work (trigger 500) in obs/search e.g. http://www.inaturalist.org/observations?hrank=species&lrank=species&place_id=1&taxon_id=40151&verifiable=true&without_taxon_id=40323%2C40325%2C40342%2C40343%2C40344%2C40345%2C40346%2C40347%2C40348%2C40349%2C40350%2C40352%2C40354%2C40509%2C40520%2C40521%2C40522%2C40523%2C40526%2C40527%2C40569%2C40614%2C40621%2C40629%2C40631%2C41143%2C41144%2C41147%2C41180%2C41182%2C41224%2C41276%2C41277%2C41301%2C41314%2C41315%2C41403%2C41406%2C41407%2C41408%2C41410%2C41411%2C41413%2C41414%2C41418%2C41421%2C41426%2C41428%2C41440%2C41446%2C41461%2C41464%2C41465%2C41478%2C41482%2C41494%2C41495%2C41496%2C41500%2C41503%2C41505%2C41509%2C41510%2C41521%2C41523%2C41525%2C41526%2C41529%2C41532%2C41534%2C41537%2C41539%2C41541%2C41543%2C41545%2C41550%2C41553%2C41558%2C41559%2C41562%2C41566%2C41569%2C41570%2C41638%2C41641%2C41644%2C41663%2C41673%2C41676%2C41691%2C41698%2C41702%2C41706%2C41708%2C41714%2C41728%2C41733%2C41740%2C41746%2C41755%2C41757%2C41766%2C41777%2C41789%2C41798%2C41799%2C41808%2C41809%2C41810%2C41815%2C41852%2C41860%2C41877%2C41879%2C41880%2C41882%2C41901%2C41970%2C41974%2C41976%2C41997%2C42007%2C42048%2C42051%2C42052%2C42066%2C42069%2C42070%2C42076%2C42077%2C42113%2C42122%2C42134%2C42161%2C42166%2C42199%2C42206%2C42210%2C42220%2C42223%2C42308%2C42310%2C42390%2C42391%2C42408%2C42412%2C42414%2C42416%2C42422%2C42426%2C42429%2C42652%2C42937%2C43101%2C43102%2C43108%2C43109%2C43110%2C43111%2C43112%2C43115%2C43116%2C43127%2C43128%2C43129%2C43130%2C43131%2C43132%2C43145%2C43149%2C43151%2C43188%2C43197%2C43335%2C43460%2C43736%2C43794%2C43840%2C43844%2C43846%2C43848%2C43997%2C44026%2C44053%2C44054%2C44055%2C44057%2C44058%2C44059%2C44060%2C44062%2C44063%2C44064%2C44065%2C44066%2C44067%2C44068%2C44069%2C44070%2C44088%2C44089%2C44090%2C44091%2C44092%2C44093%2C44094%2C44095%2C44096%2C44097%2C44104%2C44105%2C44106%2C44107%2C44110%2C44114%2C44115%2C44116%2C44117%2C44120%2C44121%2C44124%2C44125%2C44126%2C44129%2C44132%2C44148%2C44149%2C44150%2C44151%2C44154%2C44155%2C44156%2C44160%2C44162%2C44163%2C44298%2C44300%2C44306%2C44307%2C44311%2C44315%2C44316%2C44317%2C44318%2C44319%2C44323%2C44324%2C44325%2C44326%2C44329%2C44332%2C44333%2C44378%2C44387%2C44388%2C44390%2C44391%2C44392%2C44393%2C44394%2C44395%2C44396%2C44397%2C44398%2C44399%2C44414%2C44415%2C44416%2C44431%2C44432%2C44433%2C44434%2C44437%2C44469%2C44470%2C44574%2C44575%2C44576%2C44705%2C44744%2C44747%2C44748%2C44749%2C44757%2C44758%2C44759%2C44760%2C44761%2C44762%2C44899%2C44902%2C44904%2C44905%2C45044%2C45687%2C45689%2C45691%2C45708%2C45709%2C45710%2C45712%2C45714%2C45715%2C45717%2C45719%2C45720%2C45721%2C45758%2C45760%2C45761%2C45763%2C45820%2C46009%2C46017%2C46018%2C46019%2C46020%2C46023%2C46024%2C46086%2C46087%2C46092%2C46093%2C46095%2C46177%2C46178%2C46179%2C46180%2C46213%2C46215%2C46216%2C46217%2C46218%2C46219%2C46220%2C46221%2C46222%2C46225%2C46226%2C46227%2C46228%2C46229%2C46230%2C46231%2C46232%2C46233%2C46234%2C46235%2C46236%2C46237%2C46253%2C46254%2C46255%2C46256%2C46259%2C46260%2C46266%2C46272%2C46309%2C46316%2C46348%2C46352%2C46355%2C46365%2C46366%2C46368%2C46377%2C46403%2C46407%2C46415%2C46416%2C46418%2C46430%2C46433%2C46436%2C46437%2C46438%2C46445%2C46446%2C46456%2C46477%2C46487%2C46488%2C46491%2C46500%2C46503%2C46509%2C46510%2C46841%2C46883%2C46886%2C46915%2C46918%2C46994%2C47007%2C47010%2C47014%2C47049%2C47051%2C47056%2C47075%2C58393%2C59815%2C63113%2C64102%2C68093%2C74048%2C74103%2C74173%2C74204%2C74205%2C74207%2C74328%2C74359%2C74476%2C74478%2C74675%2C74677%2C74681%2C74712%2C74715%2C74719%2C74756%2C74757%2C74758%2C74824%2C74852%2C74855%2C74890%2C75053%2C75088%2C75113%2C118552%2C123070%2C148030%2C179937%2C179987%2C179988%2C179990%2C179992%2C179993%2C179994%2C179995%2C179996%2C179997%2C179998%2C179999%2C180000%2C180001%2C180002%2C180003%2C180005%2C180007%2C180008%2C180009%2C180010%2C183164%2C183166%2C197781%2C209233%2C233598%2C446640%2C520561

is there a way to remedy this? I believe we had this problem with project search params that we solved by replacing with a smaller URL param

**Comment by pleary** [comment]
There's no way to use the `without_taxon_id` param like this and get a shorter URL. Given this ticket is very old, I'm going to close it. If the same issue still requires a solution, I'd suggest opening a new ticket framed like "add this new parameter to these endpoints which will have this end result". Maybe this would need an "in_complete_set" or "not_in_incomplete_set" parameter to give you the same data with a shorter URL - I'm not sure exactly what is needed on the front end?
