### ISSUE TITLE
api / obs_search_url param for not equal to a term_value_id

### ISSUE THREAD

**Issue by loarie** [inaturalist/iNaturalistAPI#57]
I'd like an api / obs_search_url param for not equal to a term_value_id (e.g. term_value_id is NULL or != the term_value_id) - something like
```http://www.inaturalist.org/observations?place_id=any&subview=grid&term_id=9&term_value_id_not=11&order_by=votes```
which would return all observations except those with term_value_id = 11

**Comment by kueda** [comment]
Added in 7a5130577781ee25de27a42e3633ecb7ab8b9f33 (param is `without_term_value_id`)
