### ISSUE TITLE
wikipedia summary in taxon details

### ISSUE THREAD

**Issue by alexshepard** [inaturalist/iNaturalistAPI#70]
it would be great to get the wikipedia summary in taxon objects returned by the API. 

if possible, it would be great to get the summaries whenever `?details=all` is passed into the observations API, so that when I fetch observations I don't need to re-fetch the taxon objects when i display the taxon screen in the app, since this part of the app typically functions when the app is offline.

**Comment by pleary** [comment]
This should be all set now.

I'm starting to think ahead to V2 of the API, with one goal making the responses a lot smaller. Right now for example, if you fetch `http://api.inaturalist.org/v1/observations?taxon_id=27805` you'll get by default 30, but up to 100 observations, all of the same taxon, so all the metadata about the taxon is repeated 30 to 100 times, making the response very large. For this case the response is 31KB for 30 results with details, and 13KB w/o details (these might be the size of the results when gzipped, so larger if we weren't doing compression).

I'm mostly interested in keeping the size of the responses smaller, which is hard to do with the nested nature of JSON. One option is we just return a very minimal object for the taxon, like just its ID, and force the client to make API calls for the taxa they want details for. Another approach would be to denormalize the response a bit so again the observation just has a taxon_id, but later in the document we list out the full taxon object, but only do it once. Something like what you can do with YAML.

Alex, do you have any thoughts on that from an iOS perspective? How much of a pain would it be for you to have to make 2 calls - one to fetch observations, and another to fetch all their taxa in a single call (e.g. `v1/taxa/1,2,3,50,100`). And how difficult would it be to parse a non-nested JS document, or something like a YAML document with pointers in it?

**Comment by alexshepard** [comment]
I'm getting `wikipedia_summary` for http://api.inaturalist.org/v1/taxa/10094 but not http://api.inaturalist.org/v1/taxa/10325?locale=en-US

Is that expected?

**Comment by pleary** [comment]
unintentional. Should be fixed now
