### ISSUE TITLE
bounding box in projects

### ISSUE THREAD

**Issue by alexshepard** [inaturalist/iNaturalistAPI#71]
for projects that are attached to places that have bounding boxes, it would be great to know the bounding box. if we had this, when a user searched in the explore tab for a project, we could zoom the map to show the project boundaries. as the api currently exists, we can only zoom the user to the center of the project, since all we have now is latitude/longitude.

something like this would be required to fully satisfy this iOS issue: https://github.com/inaturalist/INaturalistIOS/issues/149

**Comment by pleary** [comment]
I think all was have is the lat/lng and zoom level. We already return lat/lng, so if we just add a `zoom_level` attribute would that work for you?

**Comment by alexshepard** [comment]
Sure, let's try that. Sorry for the delayed response!

**Comment by kueda** [comment]
Projects have changed a lot since 2017. Is adding `zoom_level` to the project responses still something we need?

**Comment by kueda** [comment]
I'm going to close this, but feel free to re-open if the answer is "yes"
