### ISSUE TITLE
obs field API not always returning choices

### ISSUE THREAD

**Issue by loarie** [inaturalist/iNaturalistAPI#73]
https://www.inaturalist.org/observations/upload isn't returning the https://www.inaturalist.org/observation_fields?utf8=%E2%9C%93&q=observed+by&commit=Search field
<img width="655" alt="screen shot 2017-05-30 at 9 28 24 pm" src="https://cloud.githubusercontent.com/assets/598026/26615988/21389760-4580-11e7-80b1-df03c83738c3.png">

**Comment by pleary** [comment]
Should be fixed now
