### ISSUE TITLE
created_d1 isn't time zone agnostic like d1 is

### ISSUE THREAD

**Issue by kueda** [inaturalist/iNaturalistAPI#74]
At https://github.com/inaturalist/iNaturalistAPI/blob/master/lib/controllers/v1/observations_controller.js#L547 we don't pass `dateRangeFilter()` a date field like we do when interpreting `d1`, which means requests like http://api.inaturalist.org/v1/observations?created_d1=2017-06-01 don't quite work the way you might think. Was this intentional, and if so, why? I can change this, but I want to make sure I'm not breaking something.

**Comment by pleary** [comment]
I don't think this was intentional - at least I can't think of a reason right now. I think it'd be OK to pass in `created_at_details.date` as a date field to `dateRangeFilter`
