### ISSUE TITLE
computervision/score_observation should convert to jpg

### ISSUE THREAD

**Issue by kueda** [inaturalist/iNaturalistAPI#75]
Currently it just returns an error if you ask for scores on an observation that has a non-JPEG first photo. There aren't many of those, but there are some, which makes the CV identification tools like the iOS taxon chooser behave a bit inconsistently.

IMO, not an enormous priority since most photos are JPEGs.

**Comment by pleary** [comment]
We started converting non-jpegs in the Python Vision API in inaturalist/inatVisionAPI@02ac7f8 . There isn't a restriction to JPGs on the node end anymore
