### ISSUE TITLE
Strange results with recent_taxa

### ISSUE THREAD

**Issue by loarie** [inaturalist/iNaturalistAPI#84]
Recent taxa mostly works, e.g.
```
place_id=2319
url = "http://api.inaturalist.org/v1/identifications/recent_taxa?place_id=#{place_id}&category=improving,leading&hrank=species"
uri = URI(url)
response = Net::HTTP.get(uri); nil
dat = JSON.parse(response); nil
dat["results"].map{|a| a["identification"]["observation"]["id"]}.uniq[0..10]
 => [6909037, 6908870, 6842626, 6842589, 6842401, 6122400, 365437, 6066024, 6066124, 6012523, 6048083]
```
but occasionally returns identifications that seem to be of commonly observed species (rather than 'firsts'), for example those IDs on these obs:
http://www.inaturalist.org/observations/6842626
http://www.inaturalist.org/observations/6842589
http://www.inaturalist.org/observations/6842401

Any idea why this is happening?

**Comment by pleary** [comment]
This is pretty old, but do you want to test this out again? I refactored this endpoint to calculate first observations of taxa in a different way. If it's still a problem, it would be good to have fresh examples

**Comment by kueda** [comment]
Please re-open if this is still a problem.
