### ISSUE TITLE
location in projects

### ISSUE THREAD

**Issue by alexshepard** [inaturalist/iNaturalistAPI#85]
Right now, when we fetch a project directly, such as http://api.inaturalist.org/v1/projects/642, we get the location information as `latitude` and `longitude` fields. However, when we get a project as part of an observation, such as http://api.inaturalist.org/v1/observations/7223196, we get the location information as a comma separated `location` field.

It would be great if these could be the same, so every time we get a project from the API, we can use the same mapping to parse it.

**Comment by pleary** [comment]
Ok the project objects should now be the same in each of those requests, and include both the location and lat/lng fields. I did just notice however that the project icon URLs are messed up since I changed all those Rails app config, so I'll fix those next
