### ISSUE TITLE
Set default locale and preferred place from user session

### ISSUE THREAD

**Issue by pleary** [inaturalist/iNaturalistAPI#88]
If an API call is made with an authenticated session, set default `locale` and `preferred_place_id` params based on the user's settings. These can be overridden with HTTP params

**Comment by pleary** [comment]
this should be fixed with 3642187075f5e10f2cbd5cbe5720dc0d848877ea. @alexshepard can you check to see if this helps with inaturalist/INaturalistIOS#408 ?

**Comment by alexshepard** [comment]
This is working for me @pleary. I’ve changed my site_id on iNat to germany but haven’t changed my device language or locale, and I now see explore tab and me tab taxon names in German (where there are German common names).

Thanks!
