### ISSUE TITLE
Add observations param for observations identified by a particular user

### ISSUE THREAD

**Issue by kueda** [inaturalist/iNaturalistAPI#92]
Not sure what to call it. `ident_user_id`? `identification_user_id`? `id_user_id`? Should return all observations that have an identification created by the specified user.

**Comment by vdalv** [comment]
I think this has since been implemented? https://api.inaturalist.org/v1/docs/#!/Observations/get_observations

![](https://i.imgur.com/oqZTh0s.png)

**Comment by kueda** [comment]
Added in f8d58ddf2a95ba6547ae378f2f64127872e31f47
