### ISSUE TITLE
Mark Observation Updates Seen

### ISSUE THREAD

**Issue by alexshepard** [inaturalist/iNaturalistAPI#93]
On iOS, I need a way to mark observation updates as seen using the node api, something like how we do `PUT /observations/:id/viewed_updates` on rails.

Patrick asked in chat:
> Could it be done with a "set_viewed" flag on the existing update method?

Unfortunately, no. Just because we've fetched the updates for a user doesn't mean that we know that the user has seen the updates. 

A counter-example might be: You launch the iOS app to make an observation, and we fetch your updates, marking them as `set_viewed`. Before you can switch to the Activity tab in the app, you get interrupted and close the app to do something else. Later, you login to the web and don't notice that you've got new updates because they were set as viewed by the iOS app. 

As far as I know, the red chat box on the web app works the way I'd like the iOS app to work: the chatbox shows up as red until you click the dropdown and see the updates, at which point the chatbox loses the red color. On iOS it's a little worse because we also try to fetch your updates while the iNat app is in the background. You could theoretically delete the app from your phone before you have a chance to see updates that have been downloaded via background fetch.

**Comment by alexshepard** [comment]
Thanks Patrick. Would it be possible to pass multiple observations to this?

**Comment by kueda** [comment]
Is this still something you'd like, Alex? Like so many issues in this repo, this is kind of a combined Rails / Node issue. I guess we could replicate some of the "update viewing" logic from Rails in the Node app, though that doesn't feel great.

**Comment by kueda** [comment]
Please re-open if the multiple obs things is still desired.
