### ISSUE TITLE
Localize taxon names for computervision/score_image

### ISSUE THREAD

**Issue by kueda** [inaturalist/iNaturalistAPI#94]
computervision/score_image doesn't seem to localize `preferred_common_name` based on the locale or preferred_place_id params. You just get the default English names no matter how you try to localize it. I'm guessing this has to do with parsing out that info from a multipart POST request rather than an ordinary GET.

**Comment by daniel** [comment]
Is computervision documented somewhere? I can't find it in the API docs (https://api.inaturalist.org/v1/docs/).

**Comment by pleary** [comment]
I couldn't replicate this. I was able to get localized names with different params. @kueda is this still happening for you?

@daniel the computervision API and model aren't public yet so we haven't added it to the documentation. You can read more about the CV process in these repos: https://github.com/inaturalist/inatVisionAPI , https://github.com/visipedia/tf_classification

**Comment by pleary** [comment]
Pretty sure this is fixed, so I'll close. But feel free to open with reproducible conditions
