### ISSUE TITLE
identify requests from node to rails

### ISSUE THREAD

**Issue by kueda** [inaturalist/iNaturalistAPI#95]
It would be nice in the Rails app if we knew which requests came from the node API and which didn't. I'm particularly thinking of setting the correct site for observations, which we currently do based on the host, which is always inaturalist.org for API requests. If we knew which came from the API, we could set the site based on the user's preference instead. We could use an X header for this, but it would be nice if it was something that couldn't be faked by the client, e.g. if we used `X-INat-Origin` I wouldn't want clients being able to send that header directly to Rails and pretending to be the node API. Not that I can think of how that would cause any trouble, just doesn't feel quite right.

**Comment by pleary** [comment]
I have a possible solution for this working in production. I previously committed inaturalist/inaturalistjs@43e96ee which adds a `Via: inaturalistjs` header to all inatjs requests, which the node API uses to talk to Rails. In inaturalist/inaturalist-cookbook@1c3f255 I made it so when Varnish gets this header from internal requests, it changes the value to `node-api`. Varnish also will also look for non-internal requests using header `Via: node-api` and will change those values to `user-node-api` to help prevent people from faking API requests with this header.

In inaturalist/inaturalist@203de4a I made sure Rails logs the `Via` header to logstash, so we can now search for internal node requests by filtering logstash data to `Via:node-api`.

Does this seem like a reasonable approach?

**Comment by pleary** [comment]
This is an old one without any recent activity that I think is implemented so I'm going to close it. We can use the `via` header to detect requests made from the node API to rails using the inatjs library, in addition to and distinct from other requests made from inatjs like from end-users on React pages.
