### ISSUE TITLE
Error: Cannot find module '../config'

### ISSUE THREAD

**Issue by rectoyon** [inaturalist/iNaturalistAPI#98]
i'm trying to get started with this API. After I 
```
npm install
```
I try running
```
node app.js
```
and it complains about not finding "../config"

I see a few "config" files in the root directory. Is there one I'm supposed to use?

If I try either I then get
```
Listening on 4000
{
  "code": "ECONNREFUSED",
  "errno": "ECONNREFUSED",
  "syscall": "connect",
  "address": "127.0.0.1",
  "port": 5432
}
iNaturalistAPI/lib/models/taxon.js:193
    pgClient.connection.query( query.toString( ),
                       ^
```
sorry for noob questions. I imagine I'm missing something obvious.

**Comment by kueda** [comment]
Sorry I missed this one. You need to copy `config_example.js` to `config.js`.
